Repository codestates-seb/seb42_main_025, pull requests merged in 2023-03, with the labels that each got.

#49 ♻️ 이전 jsx 삭제, TextComponent grid props 추가
  client/src/component/Buttons/HeaderButton.jsx
  client/src/component/Buttons/PatchButton.jsx
  client/src/component/Buttons/PostButton.jsx
  client/src/component/Mypage/ChatList.jsx
  client/src/component/Mypage/PostList.jsx
  client/src/component/Mypage/Profile.jsx
  client/src/component/Mypage/ProgressList.jsx
  client/src/component/Mypage/ProgressListBox.jsx
  client/src/component/Mypage/Title.jsx
  client/src/component/Text/SmallTextComponent.jsx
  client/src/component/Text/TextComponent.jsx
  client/src/component/Text/TitleComponent.jsx
  client/src/page/AuthorMypage.jsx
  client/src/page/mypage/ProgressListModule.jsx
  client/src/page/mypage/ProgressListSingleModule.jsx
  client/src/page/mypage/ProgressModule.jsx
Labels: enhancement

#56 🤡 페이지 기초 디자인 및 브랜치 교체를 위한 push
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/component/Buttons/Button.jsx
  client/src/component/ComponentBox.jsx
  client/src/component/Text/SmallTextComponent.jsx
  client/src/container/Container.jsx
  client/src/container/Header.jsx
  client/src/index.css
  client/src/page/Login.jsx
  client/src/page/chat/ChatPage.jsx
  client/src/page/chat/module/chatContent/ChatContentModule.jsx
  client/src/page/chat/module/chatContent/ChatServeModule.jsx
  client/src/page/chat/module/chatList/ChatListModule.jsx
  client/src/page/chat/module/chatList/ChatSingleListModule.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/chat/ChatModule.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/profile/ProfileModule.jsx
  client/src/page/mypage/module/progress/ProgressListModule.jsx
  client/src/page/mypage/module/progress/ProgressListSingleModule.jsx
  client/src/page/mypage/module/progress/ProgressModule.jsx
  client/src/page/post/Review.jsx
Labels: documentation, enhancement

#57 ✨ 더미 데이터, baseURL.js 생성
  client/data/dumidata.json
  client/src/api/baseURL.js
Labels: documentation

#58 ♻️ ComponentBoxes => component/BoxComponents.jsx
  client/src/component/BoxComponents.jsx/ChatCommissionInfoBox.jsx
  client/src/component/BoxComponents.jsx/ChatCommissionRequestBox.jsx
  client/src/component/BoxComponents.jsx/ChatListBox.jsx
  client/src/component/BoxComponents.jsx/CommissionListBox.jsx
  client/src/component/BoxComponents.jsx/CommissionRequestBox.jsx
  client/src/component/BoxComponents.jsx/ProgressRequestListBox.jsx
  client/src/component/BoxComponents.jsx/ReviewListBox.jsx
  client/src/component/BoxComponents.jsx/index.js
  client/src/component/ComponentBox.jsx
  client/src/page/CommissionRequest.jsx
  client/src/page/ComponentBoxesExamples.jsx
  client/src/page/chat/ChatPage.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/chat/ChatModule.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/progress/ProgressListSingleModule.jsx
  client/src/page/post/Review.jsx
Labels: documentation

#80 💄 css 수정 중간 커밋
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/component/AdComponent.jsx
  client/src/component/BoxComponents.jsx/ChatCommissionInfoBox.jsx
  client/src/component/BoxComponents.jsx/ChatListBox.jsx
  client/src/component/BoxComponents.jsx/CommissionListBox.jsx
  client/src/component/BoxComponents.jsx/CommissionRequestBox.jsx
  client/src/component/BoxComponents.jsx/ProgressRequestListBox.jsx
  client/src/component/BoxComponents.jsx/ReviewListBox.jsx
  client/src/component/Buttons/Button.jsx
  client/src/component/Carousel.jsx
  client/src/component/Editor.jsx
  client/src/component/ImageComponent.jsx
  client/src/component/InputComponent.jsx
  client/src/component/TagComponent.jsx
  client/src/component/Text/TitleTypography.jsx
  client/src/component/Text/Typography.jsx
  client/src/container/Container.jsx
  client/src/container/Footer.jsx
  client/src/container/Header.jsx
  client/src/index.css
  client/src/page/CommissionRequest.jsx
  client/src/page/ComponentBoxesExamples.jsx
  client/src/page/Login.jsx
  client/src/page/SearchPage.jsx
  client/src/page/Signup.jsx
  client/src/page/chat/ChatPage.jsx
  client/src/page/chat/module/chatContent/ChatContentModule.jsx
  client/src/page/chat/module/chatContent/ChatServeModule.jsx
  client/src/page/chat/module/chatList/ChatListModule.jsx
  client/src/page/chat/module/chatList/ChatSingleListModule.jsx
  client/src/page/home/Commission.jsx
  client/src/page/home/Home.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/chat/ChatModule.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/profile/ProfileModule.jsx
  client/src/page/mypage/module/progress/ProgressListModule.jsx
  client/src/page/mypage/module/progress/ProgressListSingleModule.jsx
  client/src/page/mypage/module/progress/ProgressModule.jsx
  client/src/page/post/Post.jsx
  client/src/page/post/PostDetail.jsx
  client/src/page/post/Review.jsx
  client/src/style/theme.js
Labels: documentation

#81 ♻️ 버튼 컴포넌트 수정
  client/src/component/Buttons/Button.jsx
  client/src/container/Header.jsx
Labels: documentation

#83 💄 컴포넌트 위치 및 display 수정, design 추가
  client/src/App.jsx
  client/src/component/BoxComponents.jsx/ChatCommissionRequestBox.jsx
  client/src/component/BoxComponents.jsx/CommissionListBox.jsx
  client/src/component/BoxComponents.jsx/index.js
  client/src/component/Carousel.jsx
  client/src/component/ImageComponent.jsx
  client/src/component/InputComponent.jsx
  client/src/component/Text/SmallTextComponent.jsx
  client/src/component/Text/TextComponent.jsx
  client/src/component/Text/TitleComponent.jsx
  client/src/component/Text/TitleTypography.jsx
  client/src/container/Header.jsx
  client/src/index.js
  client/src/page/Login.jsx
  client/src/page/Signup.jsx
  client/src/page/chat/ChatPage.jsx
  client/src/page/chat/module/ChatCommissionInfoModule.jsx
  client/src/page/chat/module/chatContent/ChatCommissionRequestModule.jsx
  client/src/page/chat/module/chatContent/ChatContentModule.jsx
  client/src/page/chat/module/chatContent/ChatServeModule.jsx
  client/src/page/chat/module/chatList/ChatListModule.jsx
  client/src/page/chat/module/chatList/ChatSingleListModule.jsx
  client/src/page/commissionRequest/CommissionRequest.jsx
  client/src/page/commissionRequest/Module/CommissionRequestBox.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/chat/ChatListModule.jsx
  client/src/page/mypage/module/chat/ChatModule.jsx
  client/src/page/mypage/module/commissions/CommissionListSingleModule.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/profile/ProfileModule.jsx
  client/src/page/mypage/module/progress/ProgressListModule.jsx
  client/src/page/mypage/module/progress/ProgressListSingleModule.jsx
  client/src/page/mypage/module/progress/ProgressRequestListModule.jsx
  client/src/page/post/Post.jsx
  client/src/page/post/PostDetail.jsx
  client/src/page/post/Review.jsx
  client/src/page/post/ReviewListModule.jsx
  client/src/style/theme.js
Labels: documentation

#88 ✨ api 및 component들 수정
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/api/baseURL.js
  client/src/apis/api/user.js
  client/src/apis/services/user.js
  client/src/apis/utils/index.js
  client/src/component/Button.jsx
  client/src/component/ImageComponent.jsx
  client/src/component/InputComponent.jsx
  client/src/component/StateComponent.jsx
  client/src/component/Typography.jsx
  client/src/container/Header.jsx
  client/src/page/CreatePost/CreatePost.jsx
  client/src/page/Login.jsx
  client/src/page/Signup.jsx
  client/src/page/chat/ChatPage.jsx
  client/src/page/chat/module/ChatCommissionInfoModule.jsx
  client/src/page/chat/module/chatContent/ChatCommissionRequestModule.jsx
  client/src/page/chat/module/chatContent/ChatContentModule.jsx
  client/src/page/chat/module/chatContent/ChatServeModule.jsx
  client/src/page/chat/module/chatList/ChatListModule.jsx
  client/src/page/chat/module/chatList/ChatSingleListModule.jsx
  client/src/page/commissionRequest/CommissionRequest.jsx
  client/src/page/commissionRequest/Module/CommissionRequestBox.jsx
  client/src/page/home/Commission.jsx
  client/src/page/home/Home.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/chat/ChatListModule.jsx
  client/src/page/mypage/module/chat/ChatModule.jsx
  client/src/page/mypage/module/commissions/CommissionListSingleModule.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/profile/ProfileModule.jsx
  client/src/page/mypage/module/progress/ProgressListModule.jsx
  client/src/page/mypage/module/progress/ProgressListSingleModule.jsx
  client/src/page/mypage/module/progress/ProgressModule.jsx
  client/src/page/mypage/module/progress/ProgressRequestListModule.jsx
  client/src/page/mypage/module/progress/ReviewModal.jsx
  client/src/page/post/Post.jsx
  client/src/page/post/PostDetail.jsx
  client/src/page/post/ReviewListModule.jsx
  client/src/state/index.js
  client/src/state/login.js
  client/src/state/member.js
  client/src/style/theme.js
Labels: documentation, enhancement

#95 ✨ mypage, commission api 연결중
  client/src/App.jsx
  client/src/api/baseURL.js
  client/src/apis/api/user.js
  client/src/apis/utils/index.js
  client/src/container/Header.jsx
  client/src/page/CreatePost/index.jsx
  client/src/page/Login.jsx
  client/src/page/Signup.jsx
  client/src/page/atom.js
  client/src/page/home/Commission.jsx
  client/src/page/home/index.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/progress/ProgressListModule.jsx
  client/src/page/post/PostDetail.jsx
  client/src/page/post/index.jsx
  client/src/state/index.js
Labels: enhancement

#106 Feat/fe01/commission api two
  client/.vscode/settings.json
  client/src/App.jsx
  client/src/apis/api/commission.js
  client/src/apis/api/commissions.js
  client/src/apis/api/user.js
  client/src/apis/utils/index.js
  client/src/component/Editor.jsx
  client/src/container/Header.jsx
  client/src/page/CreatePost/index.jsx
  client/src/page/Login.jsx
  client/src/page/Signup.jsx
  client/src/page/home/Commission.jsx
  client/src/page/home/index.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/chat/ChatListModule.jsx
  client/src/page/mypage/module/commissions/CommissionListSingleModule.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/profile/ProfileModule.jsx
  client/src/page/mypage/module/progress/ProgressModule.jsx
  client/src/page/mypage/module/progress/ReviewModal.jsx
  client/src/page/post/PostDetail.jsx
  client/src/useFetch/commissionFetch.js
  client/src/utils/PrivateRoute.jsx
  client/src/utils/Routers.jsx
Labels: documentation, enhancement

#109 Feat/fe01/merge
  client/src/apis/api/CommissionRequest.js
  client/src/apis/api/commission.js
  client/src/apis/api/trade.js
  client/src/component/Carousel.jsx
  client/src/component/Editor.jsx
  client/src/component/InputComponent.jsx
  client/src/page/CreatePost/Dropzone.jsx
  client/src/page/CreatePost/InputText.jsx
  client/src/page/CreatePost/index.jsx
  client/src/page/TragePage/Module/TradeModuleBox.jsx
  client/src/page/TragePage/TradePage.jsx
  client/src/page/chat/ChatPage.jsx
  client/src/page/chat/module/chatContent/ChatServeModule.jsx
  client/src/page/chat/module/chatContent/ChatTradeModule.jsx
  client/src/page/home/index.jsx
  client/src/page/mypage/Mypage.jsx
  client/src/page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/page/mypage/module/progress/ProgressListSingleModule.jsx
  client/src/page/mypage/module/progress/ProgressModule.jsx
  client/src/page/mypage/module/progress/ProgressTradeListModule.jsx
  client/src/page/post/PostDetail.jsx
  client/src/useFetch/getCommissionFetch.js
  client/src/useFetch/getMemberCommissionFetch.js
  client/src/useFetch/getMemberInfoFetch.js
  client/src/useFetch/getTradeFetch.js
  client/src/utils/Routers.jsx
Labels: documentation, enhancement

#110 Feat/fe03 api
  client/package-lock.json
  client/package.json
  client/src/component/TagComponent.jsx
  client/src/page/CreatePost/CreateTag.jsx
  client/src/page/CreatePost/Dropzone.jsx
  client/src/page/CreatePost/index.jsx
  client/src/page/home/Commission.jsx
  client/src/page/post/PostMain.jsx
  client/src/page/post/index.jsx
Labels: documentation, enhancement

#128 Feat/fe03 error fix
  client/src/Components/Carousel.jsx
  client/src/Components/Commissions.jsx
  client/src/Page/CreatePost/index.jsx
  client/src/Page/CreatePost/module/Dropzone.jsx
  client/src/Page/PostPage/index.jsx
  client/src/Page/PostPage/module/Post/PostDetail.jsx
  client/src/Page/PostPage/module/Post/PostImage.jsx
  client/src/apis/api/commission.js
  client/src/utils/Routers.jsx
Labels: documentation, enhancement

#134 Feat/fe01/home design recycle
  client/package-lock.json
  client/package.json
  client/src/Components/LodaingComponent.jsx
  client/src/Container/Header.jsx
  client/src/Page/LoginPage.jsx
  client/src/Page/MyPage/index.jsx
  client/src/Page/MyPage/module/Commissions/CommissionsListModule.jsx
  client/src/Page/MyPage/module/Profile/ProfileModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressListModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressListSingleModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressTradeListModule.jsx
  client/src/apis/api/commission.js
  client/src/apis/api/user.js
  client/src/customHook/getCommissionFetch.js
  client/src/customHook/getMemberInfoFetch.js
  client/src/customHook/getTradeSubInfoFetch.js
  client/src/utils/Routers.jsx
Labels: documentation, enhancement

#136 Feat/fe03 fix
  client/src/Components/Carousel.jsx
  client/src/Components/Commissions.jsx
  client/src/Components/InputComponent.jsx
  client/src/Page/CreatePost/index.jsx
  client/src/Page/CreatePost/module/CreateTag.jsx
  client/src/Page/CreatePost/module/Dropzone.jsx
  client/src/Page/CreatePost/module/InputText.jsx
  client/src/Page/HomePage/index.jsx
  client/src/Page/PostPage/index.jsx
  client/src/Page/PostPage/module/Post/PostImage.jsx
  client/src/apis/api/commission.js
  client/src/apis/api/commissions.js
  client/src/utils/Routers.jsx
  client/src/utils/imageProcess.js
Labels: documentation, enhancement

#143 :recycle: : mypage,MyPage 삭제 및 캐러셀 사진넣기
  client/src/Components/Carousel.jsx
  client/src/Page/CreatePost/index.jsx
  client/src/Page/HomePage/index.jsx
  client/src/Page/MyPage/module/Chat/ChatListModule.jsx
  client/src/Page/MyPage/module/Chat/ChatModule.jsx
  client/src/Page/MyPage/module/Commissions/CommissionListSingleModule.jsx
  client/src/Page/MyPage/module/Commissions/CommissionsListModule.jsx
  client/src/Page/MyPage/module/Profile/ProfileModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressListModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressListSingleModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressModule.jsx
  client/src/Page/MyPage/module/Progress/ProgressTradeListModule.jsx
  client/src/Page/MyPage/module/Progress/ReviewModal.jsx
  client/src/Page/mypage/index.jsx
  client/src/Page/mypage/module/chat/ChatListModule.jsx
  client/src/Page/mypage/module/chat/ChatModule.jsx
  client/src/Page/mypage/module/commissions/CommissionListSingleModule.jsx
  client/src/Page/mypage/module/commissions/CommissionsListModule.jsx
  client/src/Page/mypage/module/profile/ProfileModule.jsx
  client/src/Page/mypage/module/progress/ProgressListModule.jsx
  client/src/Page/mypage/module/progress/ProgressListSingleModule.jsx
  client/src/Page/mypage/module/progress/ProgressModule.jsx
  client/src/Page/mypage/module/progress/ProgressTradeListModule.jsx
  client/src/Page/mypage/module/progress/ReviewModal.jsx
  client/src/utils/Routers.jsx
Labels: documentation, enhancement
